name: Deploy Fargate (Simple)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }

      - name: Install dependencies
        run: npm install -g pnpm
      - run: pnpm install

      - name: Deploy to production
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: production
          cloud-url: ${{ var.PULUMI_STATE_BUCKET }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}